# Generated by Django 5.2 on 2025-07-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
