# Generated by Django 5.2 on 2025-07-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="account_number",
            field=models.CharField(default="000", max_length=20),
        ),
    ]
