# Generated by Django 5.2 on 2025-07-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="discount",
        ),
    ]
