# Generated by Django 5.2 on 2025-06-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
