# Generated by Django 5.2 on 2025-07-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quoteitem_discount_quoteitem_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
